Fix the compile error
Fix the following compile error:
| tools/header_generation/create_hdr_pbi/taal_api/pbi_hdr_ta_3_x.c: In
function 'create_pbi':
|
tools/header_generation/create_hdr_pbi/taal_api/pbi_hdr_ta_3_x.c:108:8:
error: ignoring return value of 'fread', declared with attribute
warn_unused_result [-Werror=unused-result]
| cc1: all warnings being treated as errors

Signed-off-by: Zongchun Yu <Zongchun.Yu@freescale.com>